project:
  type: book

book:
  title: "의학통계학(MED2104)"
  author: "Jongsoo Hong"
  date: "8/28/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - descriptive_statistics.qmd
    - probabilities_and_distributions.qmd
    - compare_two_groups.qmd
    - compare_more_than_three_groups.qmd
    - compare_two_proportions.qmd
    - regression.qmd
    - logistic_regression.qmd
    - survival_analysis.qmd
    - sample_size_in_clinical_trial.qmd
    - references.qmd
  
  page-navigation: true
  sidebar:
    search: true
  downloads: [pdf]
bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: superhero
    code-fold: false
    css: custom.css
#pdf:
#  documentclass: scrreprt

editor: visual

