# 두 집단의 분율비교

## Chi-square test

```{r}
library(haven)
library(ggplot2)
library(car)

data = read_sav("HN19_실습.sav")
data$sex = as.factor(data$sex)
levels(data$sex)=c("Male","Female")
data$DE1_dg = as.factor(data$DE1_dg)
levels(data$DE1_dg) = c("No", "Yes")
table(data$sex,data$DE1_dg)
round(prop.table(table(data$sex,data$DE1_dg),1),3)
chisq.test(table(data$sex,data$DE1_dg),correct=FALSE)# Asymptotic significance
chisq.test(table(data$sex,data$DE1_dg),correct=TRUE)# Continuity Correction

```

## Fisher's exact test
```{r}
data$cursmoke = as.factor(data$cursmoke)
levels(data$cursmoke) = c("No", "Yes")
table(data$cursmoke,data$DE1_dg)
round(prop.table(table(data$cursmoke,data$DE1_dg),1),3)
chisq.test(table(data$cursmoke,data$DE1_dg),correct=FALSE)# Asymptotic significance
chisq.test(table(data$cursmoke,data$DE1_dg),correct=TRUE)# Continuity Correction
fisher.test(table(data$cursmoke,data$DE1_dg))# Fisher's exact test

```
## Mantel-Haenszel chi-square test
```{r}
library(DescTools)
data$BMI_gp = ifelse(data$HE_BMI<=20, 1,
                     ifelse(data$HE_BMI<=25,2,
                            ifelse(data$HE_BMI>25,3,NA)))
data$BMI_gp = as.factor(data$BMI_gp)
levels(data$BMI_gp) = c("light","normal","heavy")
table(data$DI1_dg,data$BMI_gp)
chisq.test(table(data$DI1_dg,data$BMI_gp))
MHChisqTest(table(data$DI1_dg,data$BMI_gp))
```
## McNemar test
```{r}
data$sbp_group1 = ifelse(data$HE_sbp1<=120,"normal",
                         ifelse(data$HE_sbp1>120,"danger",NA))
data$sbp_group2 = ifelse(data$HE_sbp2<=120,"normal",
                         ifelse(data$HE_sbp2>120,"danger",NA))
table(data$sbp_group1,data$sbp_group2)
mcnemar.test(table(data$sbp_group1,data$sbp_group2),correct=F)
mcnemar.test(table(data$sbp_group1,data$sbp_group2),correct=T)
```

## Weight cases example
```{r}
test_data = matrix(c(2,28,5,25),nrow=2,ncol=2,byrow = T)
test_data
fisher.test(test_data)
```