# 기술통계

다음 데이터는 국민의 건강수준, 건강행태, 식품 및 영양섭취 실태에 대한 국가 및 시도 단위의 대표성과 신뢰성을 갖춘 통계를 산출하기 위해 매년 실시하는 국민건강영양조사 자료(2019) 중 학습과제를 위해 수정한 자료로 대상자 500명에 대한 32개 변수를 포함한 자료입니다. (HN19_실습.sav)

## 파일 불러오기

```{r}

getwd()
setwd(dir="/Users/jongsoo/Downloads")
getwd()

#| invisible(install.packages("haven",repos = 'http://cran.us.r-project.org'))
library(haven)
data = read_sav("HN19_실습.sav")
knitr::kable(head(data))
```

## 기술통계량

### 소숫점 셋째자리 반올림

### Minimum

```{r}
min(data$age)
```

### Maximum

```{r}
max(data$age)
```

### Range

```{r}
range(data$age)
range(data$age)[1]#min
range(data$age)[2]#max
```

### Quantile

```{r}
quantile(data$age,0.25)
quantile(data$age,0.75)
```

### interquartile range

```{r}
IQR(data$age)
```

### Standard devidation

```{r}
sd(data$age)
```

### Variance

```{r}
var(data$age)
```

### Skewness

```{r}
library(moments)
skewness(data$age)
```

### Kurtosis

```{r}
kurtosis(data$age)
```

```{r}
# summary: Min, 1st quartile, Median, Mean, 3rd quartile, Max
summary(data$age)
# min: minimum
min(data$age)
# max: maximum
max(data$age)
# range: range = [min, max]
range(data$age)
# quantile: 
quantile(data$age, 0.25)
# IQR: interquartile range
IQR(data$age)
# Standard devidation: 
sd(data$age)
# Variance: 
var(data$age)
# Skewness
install.packages("moments", repos = 'http://cran.us.r-project.org')
library(moments)
skewness(data$age)
# Kurtosis
kurtosis(data$age)
```

### Stem and leaf plot

```{r}
stem(data$age)
```

### Histogram

```{r}
hist(data$age)

library(ggplot2)
pp <- ggplot(data, aes(x=age)) + geom_histogram(binwidth=1, color="blue", fill="white")
pp

```

### Box plot

```{r}
boxplot(data$age)
library(ggplot2)
pp <- ggplot(data,aes(x=age)) + geom_boxplot()
pp
```

### Box plot 2 groups

```{r}
boxplot(data$age~data$sex)
library(ggplot2)
data$sex = as.factor(data$sex)
pp <- ggplot(data,aes(x=sex, y= age)) + geom_boxplot()
pp
```
