name: Render and Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          version: 1.3.353

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: | 
          Rscript -e 'install.packages(c("rmarkdown","dplyr","tidyr","arrow","data.table","fakir","tictoc","duckdb","DBI","microbenchmark","readr","fs","ggplot2","pryr","dbplyr","forcats"))'
          Rscript -e 'install.packages("polars", repos = "https://rpolars.r-universe.dev")'

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: book # By default, the current working dir is used i.e `quarto render .`

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: book
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
